# Generated by Django 3.2.4 on 2021-07-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('useradmin', models.CharField(max_length=50, verbose_name='Nombre de usuario')),
                ('contra', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Contraseña')),
            ],
        ),
    ]
