# Generated by Django 3.2.4 on 2021-07-14 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idcategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombrecategoria', models.CharField(max_length=50, verbose_name='nombre de categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='patente')),
                ('maraca', models.CharField(max_length=20, verbose_name='maraca vehiculo')),
                ('modelo', models.CharField(blank=True, max_length=20, null=True, verbose_name='modelo')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.categoria')),
            ],
        ),
    ]
